// playwright.config.ts
import { defineConfig } from '@playwright/test';
import * as dotenv from 'dotenv';

dotenv.config();

export default defineConfig({
  // General Playwright use options for your tests
  use: {
    trace: 'on', // Record trace for debugging
    video: 'retain-on-failure', // Record video and retain if test fails
    browserName: 'chromium', // Default browser (can be overridden in projects or step definitions)
    // You might add baseURL here if all your tests hit the same domain
    // baseURL: 'https://www.example.com',
  },
  // Projects allow you to run tests in different configurations (e.g., different browsers, devices)
  projects: [
    {
      name: 'Local-Chrome', // A more descriptive name for your local Chrome setup
      use: {
        browserName: 'chromium',
        // channel: 'chrome', // Use the 'chrome' channel for a specific Chrome browser install
      },
    },
    // Your BrowserStack project configuration
    // This assumes you have BrowserStack setup correctly in your steps/world
    {
      name: 'BrowserStack-Chrome',
      use: {
        browserName: 'chromium',
        channel: 'chrome', // You might need to adjust this depending on BrowserStack's setup
        // Add BrowserStack specific capabilities here if you use Playwright's API directly
        // For Cucumber, these might be handled in your CustomWorld based on environment variables
      },
    },
  ],
  // The 'reporter' in playwright.config.ts is for Playwright's native test runner (`npx playwright test`).
  // It does NOT affect the Allure reports generated by Cucumber.js.
  reporter: [['list']], // Keeps your console output clean for Playwright's runner if you ever use it.
  workers: 1, // Number of parallel workers
  retries: 1, // Number of retries for failed tests
});